using DotNetStarterProject.Models;
using Microsoft.AspNetCore.Mvc;
using Npgsql;
using System.Diagnostics;

namespace DotNetStarterProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly IConfiguration _configuration;

        public HomeController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var connectionString = _configuration.GetConnectionString("DefaultConnection")
                ?? throw new InvalidOperationException("Connection string 'DefaultConnection' is not configured.");

            var sampleItems = new List<SampleItem>();

            await using var connection = new NpgsqlConnection(connectionString);
            await connection.OpenAsync();

            await using (var setupCommand = new NpgsqlCommand("""
                create table if not exists sample_items (
                    id integer generated by default as identity primary key,
                    name text not null unique,
                    description text not null,
                    created_at timestamp with time zone not null default now()
                );

                insert into sample_items (name, description)
                values
                    ('First sample', 'PostgreSQLから取得したサンプルデータです。'),
                    ('Second sample', 'GETリクエストでホーム画面に表示しています。'),
                    ('Third sample', 'sample_items テーブルに保存されています。')
                on conflict (name) do nothing;
                """, connection))
            {
                await setupCommand.ExecuteNonQueryAsync();
            }

            await using (var selectCommand = new NpgsqlCommand("""
                select id, name, description, created_at
                from sample_items
                order by id;
                """, connection))
            await using (var reader = await selectCommand.ExecuteReaderAsync())
            {
                while (await reader.ReadAsync())
                {
                    sampleItems.Add(new SampleItem
                    {
                        Id = reader.GetInt32(0),
                        Name = reader.GetString(1),
                        Description = reader.GetString(2),
                        CreatedAt = reader.GetDateTime(3)
                    });
                }
            }

            return View(sampleItems);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}
